name: flutter_app_1
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
   # contactFeatures
   

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.0.6 
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11

 
flutter:
    uses-material-design: true
    assets:
      - assets/images/slider1.jpg
      - assets/images/slider2.jpg
      - assets/images/slider3.jpg
      - assets/images/products/
      - assets/files/
      - assets/images/
 