// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFTJQg00CdrHfZL1KGOGEQDnQwEApecDM',
    appId: '1:672981973037:web:da715dc86e7bb1f031e0a4',
    messagingSenderId: '672981973037',
    projectId: 'flutterapp1-b5e72',
    authDomain: 'flutterapp1-b5e72.firebaseapp.com',
    storageBucket: 'flutterapp1-b5e72.firebasestorage.app',
    measurementId: 'G-W3GZ912PMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNTCZOamcYZeqyp72YXfPDKNZEA8ri1I',
    appId: '1:672981973037:android:6b257be6abe2385931e0a4',
    messagingSenderId: '672981973037',
    projectId: 'flutterapp1-b5e72',
    storageBucket: 'flutterapp1-b5e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqnhFkCvyaMPDg1lo3D-q35F604fuKrLQ',
    appId: '1:672981973037:ios:9f59f4477c728a8931e0a4',
    messagingSenderId: '672981973037',
    projectId: 'flutterapp1-b5e72',
    storageBucket: 'flutterapp1-b5e72.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqnhFkCvyaMPDg1lo3D-q35F604fuKrLQ',
    appId: '1:672981973037:ios:9f59f4477c728a8931e0a4',
    messagingSenderId: '672981973037',
    projectId: 'flutterapp1-b5e72',
    storageBucket: 'flutterapp1-b5e72.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFTJQg00CdrHfZL1KGOGEQDnQwEApecDM',
    appId: '1:672981973037:web:f3af566b19d612a531e0a4',
    messagingSenderId: '672981973037',
    projectId: 'flutterapp1-b5e72',
    authDomain: 'flutterapp1-b5e72.firebaseapp.com',
    storageBucket: 'flutterapp1-b5e72.firebasestorage.app',
    measurementId: 'G-80YN3BK7FP',
  );
}
